langsList = ("Русский", "English")

RU = {
"connectError" : "Ошибка подключения",
"connectErrorText" : "Произошла ошибка подключения к серверу. Повторите попытку позже.",
"nextButton" : "Продолжить",
"backButton" : "Назад",
"descServer" : "Описание сервера:",
"serverPort" : "Порт сервера:",
"playersCount" : "Кол-во игроков:",
"onlineMode" : "Онлайн-режим",
"commandBlocks" : "Командные блоки",
"serverDifficulty" : "Сложность:",
"serverVersion" : "Версия:",
"difficultyList" : ['Мирная', 'Легкая', 'Нормальная', 'Сложная'],
"allowPVP" : "Разрешить PVP",
"choosePluginsToInstall" : "Выберите плагины, которые вы хотите установить:",
"chooseDirectory" : "Выберите папку",
"buildButton" : "Собрать",
"chooseDirectoryToSaveServer" : "Пожалуйста, выберите папку в которой будет сохранен собранный сервер:",
"pleaseWaitServerBuilding" : "Пожалуйста подождите, идет сборка сервера...",
"wellDone" : "Сборка сервера была успешно завершена.\nБлагодарим за использование продуктов Upbits.\nУдачной игры!",
"donateButton" : "Пожертвовать",
"closeButton" : "Закрыть",
"downloadingServer" : "Загрузка сервера...",
"unpackingServer" : "Распаковка сервера...",
"removeCache" : "Удаление кэша...",
"downloadingCore" : "Загрузка ядра...",
"downloading" : "Загрузка ",
"settings" : "Настройка параметров..."
}

EN = {
"connectError" : "Connection error.",
"connectErrorText" : "An error occurred while connecting to the server. Please try again later.",
"nextButton" : "Continue",
"backButton" : "Go Back",
"descServer" : "Server Description:",
"serverPort" : "Server Port:",
"playersCount" : "Players Count:",
"onlineMode" : "Online-mode",
"commandBlocks" : "Command Blocks",
"serverDifficulty" : "Difficulty:",
"serverVersion" : "Version:",
"difficultyList" : ['Peaceful', 'Easy', 'Normal', 'Hard'],
"allowPVP" : "Allow PVP",
"choosePluginsToInstall" : "Select the plugins you want to install:",
"chooseDirectory" : "Select folder",
"buildButton" : "Build",
"chooseDirectoryToSaveServer" : "           Please select the folder in which the collected server will be saved:",
"pleaseWaitServerBuilding" : "Please wait, server assembly is in progress...",
"wellDone" : "The server was successfully assembled.\nWe thank you for using the Upbits products.\nThank you!",
"donateButton" : "Donate",
"closeButton" : "Close",
"downloadingServer" : "Downloading server...",
"unpackingServer" : "Unpacking server...",
"removeCache" : "Removing cache...",
"downloadingCore" : "Downloading core...",
"downloading" : "Downloading ",
"settings" : "Settings..."
}
